// Bot data types and predefined bots
// Easy to add new bots - just add to the appropriate category array

export interface Bot {
  id: string;
  nameKey: string; // Translation key for bot name
  nameEnglish: string; // English name
  namePersian: string; // Persian name
  rating: number;
  descriptionKey: string; // Translation key for description
  descriptionEnglish: string; // English description
  descriptionPersian: string; // Persian description
  category: BotCategory;
  image?: string; // Path to bot image
  country?: string | string[]; // Country code(s) for flag (e.g., "us", "ru", or ["fr", "ir"])
  greeting?: string; // Custom greeting translation key
  cardStyle?: "golden"; // Special card appearance style
}

export type CardStyle = "golden";

export type BotCategory =
  | "Beginner"
  | "Intermediate"
  | "Advanced"
  | "Master"
  | "Champions"
  | "Musicians"
  | "TopPlayers"
  | "Engine"
  | "Custom";

export const BOT_CATEGORIES: BotCategory[] = [
  "Beginner",
  "Intermediate",
  "Advanced",
  "Master",
  "Champions",
  "Musicians",
  "TopPlayers",
  "Engine",
];

// ============================================================
// BEGINNER BOTS (400-800 Elo)
// ============================================================
export const BEGINNER_BOTS: Bot[] = [
  {
    id: "martin",
    nameKey: "Bots.Bot.Martin.Name",
    nameEnglish: "Martin",
    namePersian: "مارتین",
    rating: 400,
    descriptionKey: "Bots.Bot.Martin.Desc",
    descriptionEnglish: "A friendly beginner bot that has just learned the rules.",
    descriptionPersian: "ربات مبتدی دوستانه که تازه قوانین را یاد گرفته است.",
    category: "Beginner",
    image: "/bots/beginner/martin.png",
  },
  {
    id: "wayne",
    nameKey: "Bots.Bot.Wayne.Name",
    nameEnglish: "Wayne",
    namePersian: "وین",
    rating: 428,
    descriptionKey: "Bots.Bot.Wayne.Desc",
    descriptionEnglish: "A beginner bot that makes simple moves.",
    descriptionPersian: "ربات مبتدی که حرکت‌های ساده انجام می‌دهد.",
    category: "Beginner",
    image: "/bots/beginner/wayne.png",
  },
  {
    id: "fabian",
    nameKey: "Bots.Bot.Fabian.Name",
    nameEnglish: "Fabian",
    namePersian: "فابیان",
    rating: 457,
    descriptionKey: "Bots.Bot.Fabian.Desc",
    descriptionEnglish: "A beginner bot with basic strategies.",
    descriptionPersian: "ربات مبتدی با استراتژی‌های پایه.",
    category: "Beginner",
    image: "/bots/beginner/fabian.png",
  },
  {
    id: "juan",
    nameEnglish: "Juan",
    namePersian: "جان",
    nameKey: "Bots.Bot.Juan.Name",
    rating: 485,
    descriptionKey: "Bots.Bot.Juan.Desc",
    descriptionEnglish: "A beginner bot that learns simple tactical patterns.",
    descriptionPersian: "ربات مبتدی که الگوهای تاکتیکی ساده را یاد می‌گیرد.",
    category: "Beginner",
    image: "/bots/beginner/juan.png",
  },
  {
    id: "filip",
    nameEnglish: "Filip",
    namePersian: "فیلیپ",
    nameKey: "Bots.Bot.Filip.Name",
    rating: 514,
    descriptionKey: "Bots.Bot.Filip.Desc",
    descriptionEnglish: "A beginner bot with calm and steady moves.",
    descriptionPersian: "ربات مبتدی با حرکت‌های آرام و ثابت.",
    category: "Beginner",
    image: "/bots/beginner/filip.png",
  },
  {
    id: "elani",
    nameEnglish: "Elani",
    namePersian: "الانی",
    nameKey: "Bots.Bot.Elani.Name",
    rating: 543,
    descriptionKey: "Bots.Bot.Elani.Desc",
    descriptionEnglish: "A beginner bot that is a member of the chess club.",
    descriptionPersian: "ربات مبتدی عضو باشگاه شطرنج مدرسه.",
    category: "Beginner",
    image: "/bots/beginner/elani.png",
  },
  {
    id: "noel",
    nameEnglish: "Noel",
    namePersian: "نوئل",
    nameKey: "Bots.Bot.Noel.Name",
    rating: 571,
    descriptionKey: "Bots.Bot.Noel.Desc",
    descriptionEnglish: "A beginner bot that is a chess enthusiast who learns tactical patterns.",
    descriptionPersian: "ربات مبتدی کنجکاو که الگوهای تاکتیکی را یاد می‌گیرد.",
    category: "Beginner",
    image: "/bots/beginner/noel.png",
  },
  {
    id: "oliver",
    nameEnglish: "Oliver",
    namePersian: "اولیور",
    nameKey: "Bots.Bot.Oliver.Name",
    rating: 600,
    descriptionKey: "Bots.Bot.Oliver.Desc",
    descriptionEnglish: "A beginner bot with basic knowledge.",
    descriptionPersian: "ربات مبتدی با دانش پایه.",
    category: "Beginner",
    image: "/bots/beginner/oliver.png",
  },
  {
    id: "milica",
    nameEnglish: "Milica",
    namePersian: "میلیکا",
    nameKey: "Bots.Bot.Milica.Name",
    rating: 628,
    descriptionKey: "Bots.Bot.Milica.Desc",
    descriptionEnglish: "A beginner bot that likes simple moves.",
    descriptionPersian: "ربات مبتدی که حرکت‌های ساده دوست دارد.",
    category: "Beginner",
    image: "/bots/beginner/milica.png",
  },
  {
    id: "aron",
    nameEnglish: "Aron",
    namePersian: "آرون",
    nameKey: "Bots.Bot.Aron.Name",
    rating: 657,
    descriptionKey: "Bots.Bot.Aron.Desc",
    descriptionEnglish: "A beginner bot with basic strategies.",
    descriptionPersian: "ربات مبتدی با استراتژی‌های ابتدایی.",
    category: "Beginner",
    image: "/bots/beginner/aron.png",
  },
  {
    id: "janjay",
    nameEnglish: "Janjay",
    namePersian: "جانجای",
    nameKey: "Bots.Bot.Janjay.Name",
    rating: 685,
    descriptionKey: "Bots.Bot.Janjay.Desc",
    descriptionEnglish: "A friendly beginner bot.",
    descriptionPersian: "ربات مبتدی دوستانه.",
    category: "Beginner",
    image: "/bots/beginner/janjay.png",
  },
  {
    id: "mina",
    nameEnglish: "Mina",
    namePersian: "مینا",
    nameKey: "Bots.Bot.Mina.Name",
    rating: 714,
    descriptionKey: "Bots.Bot.Mina.Desc",
    descriptionEnglish: "A beginner bot that learns the rules.",
    descriptionPersian: "ربات مبتدی که قوانین را یاد می‌گیرد.",
    category: "Beginner",
    image: "/bots/beginner/mina.png",
  },
  {
    id: "zara",
    nameEnglish: "Zara",
    namePersian: "زارا",
    nameKey: "Bots.Bot.Zara.Name",
    rating: 743,
    descriptionKey: "Bots.Bot.Zara.Desc",
    descriptionEnglish: "A beginner bot with basic moves.",
    descriptionPersian: "ربات مبتدی با حرکت‌های پایه.",
    category: "Beginner",
    image: "/bots/beginner/zara.png",
  },
  {
    id: "santiago",
    nameEnglish: "Santiago",
    namePersian: "سانتیاگو",
    nameKey: "Bots.Bot.Santiago.Name",
    rating: 771,
    descriptionKey: "Bots.Bot.Santiago.Desc",
    descriptionEnglish: "A beginner bot that is a chess enthusiast.",
    descriptionPersian: "ربات مبتدی کنجکاو.",
    category: "Beginner",
    image: "/bots/beginner/santiago.png",
  },
  {
    id: "karim",
    nameEnglish: "Karim",
    namePersian: "کریم",
    nameKey: "Bots.Bot.Karim.Name",
    rating: 800,
    descriptionKey: "Bots.Bot.Karim.Desc",
    descriptionEnglish: "A beginner bot with basic chess knowledge.",
    descriptionPersian: "ربات مبتدی با دانش پایه شطرنج.",
    category: "Beginner",
    image: "/bots/beginner/karim.png",
  },
];

// ============================================================
// INTERMEDIATE BOTS (800-1200 Elo)
// ============================================================
export const INTERMEDIATE_BOTS: Bot[] = [
  {
    id: "Maria-Bot",
    nameEnglish: "Maria",
    namePersian: "ماریا",
    nameKey: "bot.name.maria",
    rating: 1500,
    descriptionKey: "bot.description.maria",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/maria.png",
  },
  {
    id: "Maxim-Bot",
    nameEnglish: "Maxim",
    namePersian: "ماکسیم",
    nameKey: "bot.name.maxim",
    rating: 1500,
    descriptionKey: "bot.description.maxim",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/maxim.png",
  },
  {
    id: "Hans-Bot",
    nameEnglish: "Hans",
    namePersian: "هانس",
    nameKey: "bot.name.hans",
    rating: 1500,
    descriptionKey: "bot.description.hans",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/hans.png",
  },
  {
    id: "Azeez-Bot",
    nameEnglish: "Azeez",
    namePersian: "عزیز",
    nameKey: "bot.name.azeez",
    rating: 1500,
    descriptionKey: "bot.description.azeez",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/azeez.png",
  },
  {
    id: "Laura-Bot",
    nameEnglish: "Laura",
    namePersian: "لورا",
    nameKey: "bot.name.laura",
    rating: 1500,
    descriptionKey: "bot.description.laura",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/laura.png",
  },
  {
    id: "Sven-Bot",
    nameEnglish: "Sven",
    namePersian: "سون",
    nameKey: "bot.name.sven",
    rating: 1500,
    descriptionKey: "bot.description.sven",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/sven.png",
  },
  {
    id: "Emir-Bot",
    nameEnglish: "Emir",
    namePersian: "امیر",
    nameKey: "bot.name.emir",
    rating: 1500,
    descriptionKey: "bot.description.emir",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/emir.png",
  },
  {
    id: "Elena-Bot",
    nameEnglish: "Elena",
    namePersian: "النا",
    nameKey: "bot.name.elena",
    rating: 1500,
    descriptionKey: "bot.description.elena",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/elena.png",
  },
  {
    id: "Wilson-Bot",
    nameEnglish: "Wilson",
    namePersian: "ویلسون",
    nameKey: "bot.name.wilson",
    rating: 1500,
    descriptionKey: "bot.description.wilson",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/wilson.png",
  },
  {
    id: "Vinh-Bot",
    nameEnglish: "Vinh",
    namePersian: "وین",
    nameKey: "bot.name.vinh",
    rating: 1500,
    descriptionKey: "bot.description.vinh",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/vinh.png",
  },
  {
    id: "Nelson-Bot",
    nameEnglish: "Nelson",
    namePersian: "نلسون",
    nameKey: "bot.name.nelson",
    rating: 1500,
    descriptionKey: "bot.description.nelson",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/nelson.png",
  },
  {
    id: "Jade-Bot",
    nameEnglish: "Jade",
    namePersian: "جِید",
    nameKey: "bot.name.jade",
    rating: 1500,
    descriptionKey: "bot.description.jade",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/jade.png",
  },
  {
    id: "David-Bot",
    nameEnglish: "David",
    namePersian: "دیوید",
    nameKey: "bot.name.david",
    rating: 1500,
    descriptionKey: "bot.description.david",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/david.png",
  },
  {
    id: "Ali-Bot",
    nameEnglish: "Ali",
    namePersian: "علی",
    nameKey: "bot.name.ali",
    rating: 1500,
    descriptionKey: "bot.description.ali",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/ali.png",
  },
  {
    id: "Mateo-Bot",
    nameEnglish: "Mateo",
    namePersian: "متیو",
    nameKey: "bot.name.mateo",
    rating: 1500,
    descriptionKey: "bot.description.mateo",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/mateo.png",
  },
];

// ============================================================
// ADVANCED BOTS (1200-1600 Elo)
// ============================================================
export const ADVANCED_BOTS: Bot[] = [
  {
    id: "wendy-bot",
    nameEnglish: "Wendy",
    namePersian: "وندی",
    nameKey: "bot.name.wendy",
    rating: 1750,
    descriptionKey: "bot.description.wendy",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی پیشرفته با گرایش تهاجمی و توان بالا در تاکتیک‌های موقعیتی؛ مناسب برای بازیکنان میانه‌تاپیشرفته که دنبال تمرین محاسبات تاکتیکی هستند.",
    category: "Advanced",
    image: "/bots/advanced/wendy.png",
    greeting: "bot.greeting.wendy",
  },
  {
    id: "Antonio-Bot",
    nameEnglish: "Antonio",
    namePersian: "آنتونیو",
    nameKey: "bot.name.antonio",
    rating: 1850,
    descriptionKey: "bot.description.antonio",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی با سبک بازی متعادل و استحکام موقعیتی؛ کمتر ریسک‌پذیر و مناسب برای تمرین خط‌مشی‌های پوزیسیونی.",
    category: "Advanced",
    image: "/bots/advanced/antonio.png",
    country: "es",
    greeting: "bot.greeting.antonio",
  },
  {
    id: "Pierre-Bot",
    nameEnglish: "Pierre",
    namePersian: "پیر",
    nameKey: "bot.name.pierre",
    rating: 1900,
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی تکنیکی و محاسباتی که به برنامه‌ریزی بلندمدت و اجرای طرح‌های میانه‌بازی توجه دارد؛ مناسب برای تمرین بازی موقعیتی و انتهای بازی.",
    descriptionKey: "bot.description.pierre",
    category: "Advanced",
    image: "/bots/advanced/pierre.png",
    country: "fr",
    greeting: "bot.greeting.pierre",
  },
  {
    id: "Pablo-Bot",
    nameEnglish: "Pablo",
    namePersian: "پابلو",
    nameKey: "bot.name.pablo",
    rating: 1700,
    descriptionKey: "bot.description.pablo",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی هجومی-تاکتیکی که در موقعیت‌های باز بسیار خطرناک است؛ برای تمرین حمله و محاسبات ترکیبی مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/pablo.png",
    country: "es",
    greeting: "bot.greeting.pablo",
  },
  {
    id: "Joel-Bot",
    nameEnglish: "Joel",
    namePersian: "جول",
    nameKey: "bot.name.joel",
    rating: 1800,
    descriptionKey: "bot.description.joel",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی با سبک همه‌کاره که تعادل خوبی بین تاکتیک و پوزیسیون دارد؛ گزینه‌ای مناسب برای بازیکنانی که می‌خواهند جنبه‌های مختلف بازی را تمرین کنند.",
    category: "Advanced",
    image: "/bots/advanced/joel.png",
    greeting: "bot.greeting.joel",
  },
  {
    id: "Isabel-Bot",
    nameEnglish: "Isabel",
    namePersian: "ایزابل",
    nameKey: "bot.name.isabel",
    rating: 1950,
    descriptionKey: "bot.description.isabel",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی با دقت بالا در محاسبات و تسلط بر انتهای بازی؛ برای تمرین تبدیل مزیت به پیروزی و مطالعه انتهای بازی مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/isabel.png",
    country: "es",
    greeting: "bot.greeting.isabel",
  },
  {
    id: "Arthur-Bot",
    nameEnglish: "Arthur",
    namePersian: "آرتور",
    nameKey: "bot.name.arthur",
    rating: 2000,
    descriptionKey: "bot.description.arthur",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی کلاسیک و ساخت‌یافته که به اصول بنیادین شطرنج پایبند است؛ مناسب برای آشنایی با خطوط اصلی و استراتژی‌های کلاسیک.",
    category: "Advanced",
    image: "/bots/advanced/arthur.png",
    country: "gb",
    greeting: "bot.greeting.arthur",
  },
  {
    id: "Jonas-Bot",
    nameEnglish: "Jonas",
    namePersian: "جوناس",
    nameKey: "bot.name.jonas",
    rating: 1780,
    descriptionKey: "bot.description.jonas",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی منعطف که بین بازی حفاظتی و هجومی تغییر سبک می‌دهد؛ برای بررسی پاسخ‌های مختلف به گشایش‌های متنوع مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/jonas.png",
    country: "se",
    greeting: "bot.greeting.jonas",
  },
  {
    id: "Isla-Bot",
    nameEnglish: "Isla",
    namePersian: "ایسلا",
    nameKey: "bot.name.isla",
    rating: 1670,
    descriptionKey: "bot.description.isla",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی که تمایل به بازی باز و پویایی دارد؛ مناسب برای تمرین بازی‌های تاکتیکی و تمرکز بر محاسبات کوتاه‌مدت.",
    category: "Advanced",
    image: "/bots/advanced/isla.png",
    greeting: "bot.greeting.isla",
  },
  {
    id: "Lorenzo-Bot",
    nameEnglish: "Lorenzo",
    namePersian: "لورنزو",
    nameKey: "bot.name.lorenzo",
    rating: 1820,
    descriptionKey: "bot.description.lorenzo",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی با تاکید بر بازی موقعیتی و مدیریت ساختار پیاده؛ برای تمرین برنامه‌ریزی میانه‌بازی مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/lorenzo.png",
    country: "it",
    greeting: "bot.greeting.lorenzo",
  },
  {
    id: "Wally-Bot",
    nameEnglish: "Wally",
    namePersian: "والی",
    nameKey: "bot.name.wally",
    rating: 1600,
    descriptionKey: "bot.description.wally",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی نسبتاً سازگار برای تمرین بازیکنانی که می‌خواهند در برابر بازی‌های غیرمنتظره و اشتباهات حریف تمرین کنند.",
    category: "Advanced",
    image: "/bots/advanced/wally.png",
    greeting: "bot.greeting.wally",
  },
  {
    id: "Julia-Bot",
    nameEnglish: "Julia",
    namePersian: "جولیا",
    nameKey: "bot.name.julia",
    rating: 1880,
    descriptionKey: "bot.description.julia",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی دقیق با توانایی‌های تاکتیکی و استراتژیک؛ مناسب برای تمرین هماهنگی حمله و دفاع در میانه‌بازی.",
    category: "Advanced",
    image: "/bots/advanced/julia.png",
    country: "de",
    greeting: "bot.greeting.julia",
  },
  {
    id: "Miguel-Bot",
    nameEnglish: "Miguel",
    namePersian: "میگل",
    nameKey: "bot.name.miguel",
    rating: 1740,
    descriptionKey: "bot.description.miguel",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی هجومی با تمایل به ایجاد پیچیدگی‌های تاکتیکی؛ برای تمرین حملات برنده‌ساز و محاسبات ترکیبی مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/miguel.png",
    country: "es",
    greeting: "bot.greeting.miguel",
  },
  {
    id: "Xavier-Bot",
    nameEnglish: "Xavier",
    namePersian: "خاویر",
    nameKey: "bot.name.xavier",
    rating: 1920,
    descriptionKey: "bot.description.xavier",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی فنی با تمرکز بر دقت محاسبات و برنامه‌ریزی؛ مناسب برای تمرین بازی‌های پیچیده و حفظ مزیت فنی.",
    category: "Advanced",
    image: "/bots/advanced/xavier.png",
    country: "fr",
    greeting: "bot.greeting.xavier",
  },
  {
    id: "Olga-Bot",
    nameEnglish: "Olga",
    namePersian: "اولگا",
    nameKey: "bot.name.olga",
    rating: 1700,
    descriptionKey: "bot.description.olga",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی که ترکیبی از بازی دفاعی قوی و حملات سریع را ارائه می‌دهد؛ برای تمرین واکنش به تهدیدات ناگهانی مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/olga.png",
    country: "ru",
    greeting: "bot.greeting.olga",
  },
  {
    id: "Li-Bot",
    nameEnglish: "Li",
    namePersian: "لی",
    nameKey: "bot.name.li",
    rating: 1650,
    descriptionKey: "bot.description.li",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی چابک با تمایل به بازی‌های ترکیبی سریع؛ برای تمرین تاکتیک‌های موقعیتی و محاسبات سریع مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/li.png",
    country: "cn",
    greeting: "bot.greeting.li",
  },
  {
    id: "Charles-Bot",
    nameEnglish: "Charles",
    namePersian: "چارلز",
    nameKey: "bot.name.charles",
    rating: 1970,
    descriptionKey: "bot.description.charles",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی با سبک کلاسیک و تیز در محاسبات؛ مناسب برای بازیکنانی که می‌خواهند با سبک اصولی و دقیق تمرین کنند.",
    category: "Advanced",
    image: "/bots/advanced/charles.png",
    country: "gb",
    greeting: "bot.greeting.charles",
  },
  {
    id: "Fatima-Bot",
    nameEnglish: "Fatima",
    namePersian: "فاطیما",
    nameKey: "bot.name.fatima",
    rating: 1680,
    descriptionKey: "bot.description.fatima",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی چندوجهی با واکنش‌های هوشمندانه به اشتباهات حریف؛ برای تمرین بهره‌برداری از موقعیت‌های کوچک مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/fatima.png",
    greeting: "bot.greeting.fatima",
  },
  {
    id: "Manuel-Bot",
    nameEnglish: "Manuel",
    namePersian: "مانوئل",
    nameKey: "bot.name.manuel",
    rating: 1830,
    descriptionKey: "bot.description.manuel",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی با استحکام پوزیسیونی و توانایی بازی در سطوح میانه تا پیشرفته؛ مناسب برای تمرین ساختارهای پیاده و میانه‌بازی.",
    category: "Advanced",
    image: "/bots/advanced/manuel.png",
    country: "es",
    greeting: "bot.greeting.manuel",
  },
  {
    id: "Oscar-Bot",
    nameEnglish: "Oscar",
    namePersian: "اسکار",
    nameKey: "bot.name.oscar",
    rating: 1760,
    descriptionKey: "bot.description.oscar",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی منعطف با قابلیت ایجاد فشار در میانه‌بازی و تبدیل اشتباهات حریف به برتری؛ مناسب برای تمرین فشار مداوم.",
    category: "Advanced",
    image: "/bots/advanced/oscar.png",
    greeting: "bot.greeting.oscar",
  },
];

// ============================================================
// MASTER BOTS (1600-2200 Elo)
// ============================================================
export const MASTER_BOTS: Bot[] = [
  {
    id: "nora-master-001",
    nameEnglish: "Nora",
    namePersian: "نورا",
    nameKey: "bot.name.nora",
    rating: 2600,
    descriptionKey: "bot.description.nora",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "یک استاد تهاجمی با گرایش به بازی ترکیبی و حملات سریع؛ رفتار آموزشی دارد و پس از هر اشتباه، توضیح مختصر می‌دهد.",
    category: "Master",
    image: "/bots/master/nora.png",
    country: "us",
    greeting: "bot.greeting.nora",
  },
  {
    id: "noam-master-002",
    nameEnglish: "Noam",
    namePersian: "نوآم",
    nameKey: "bot.name.noam",
    rating: 2700,
    descriptionKey: "bot.description.noam",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "استادی محاسبه‌گر و دفاعی که تکیه‌گاه استراتژی طولانی‌مدت است؛ مناسب بازیکنانی که می‌خواهند محاسبات انتهایی را تقویت کنند.",
    category: "Master",
    image: "/bots/master/noam.png",
    country: "il",
    greeting: "bot.greeting.noam",
  },
  {
    id: "ahmed-master-003",
    nameEnglish: "Ahmed",
    namePersian: "احمد",
    nameKey: "bot.name.ahmed",
    rating: 2550,
    descriptionKey: "bot.description.ahmed",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "استادی متعادل با اولویت کنترل مرکز و بازی پوزیسیونی؛ توضیحات کوتاه‌وکاربردی در مورد اشتباهات می‌دهد.",
    category: "Master",
    image: "/bots/master/ahmed.png",
    country: "eg",
    greeting: "bot.greeting.ahmed",
  },
  {
    id: "sakura-master-004",
    nameEnglish: "Sakura",
    namePersian: "ساکورا",
    nameKey: "bot.name.sakura",
    rating: 2500,
    descriptionKey: "bot.description.sakura",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رویکرد خلاقانه و دید تاکتیکی بالا؛ ترکیب‌های غیرمتعارف را دوست دارد و برای تمرین تاکتیک مناسب است.",
    category: "Master",
    image: "/bots/master/sakura.png",
    country: "jp",
    greeting: "bot.greeting.sakura",
  },
  {
    id: "arjun-master-005",
    nameEnglish: "Arjun",
    namePersian: "آرجون",
    nameKey: "bot.name.arjun",
    rating: 2650,
    descriptionKey: "bot.description.arjun",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "استادی محکم با مبانی نظری قوی؛ به بازیکنان کمک می‌کند ایده‌های بازی وسط را بهتر درک کنند و پایان‌بازی‌ها را تقویت می‌کند.",
    category: "Master",
    image: "/bots/master/arjun.png",
    country: "in",
    greeting: "bot.greeting.arjun",
  },
  {
    id: "francis-master-006",
    nameEnglish: "Francis",
    namePersian: "فرانسیس",
    nameKey: "bot.name.francis",
    rating: 2620,
    descriptionKey: "bot.description.francis",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رویه‌ای متفکر و حساب‌شده؛ مناسب برای مطالعه بازی‌های استراتژیک و بازنمایی ایده‌های کلاسیک شطرنج.",
    category: "Master",
    image: "/bots/master/francis.png",
    country: "fr",
    greeting: "bot.greeting.francis",
  },
  {
    id: "sofia-master-007",
    nameEnglish: "Sofia",
    namePersian: "صوفیا",
    nameKey: "bot.name.sofia",
    rating: 2580,
    descriptionKey: "bot.description.sofia",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "سبک بازی انعطاف‌پذیر؛ ترکیبی از برنامه‌ریزی پوزیسیونی و واکنش‌های تاکتیکی سریع، مناسب بازیکنان میانی-پیشرفته.",
    category: "Master",
    image: "/bots/master/sofia.png",
    country: "bg",
    greeting: "bot.greeting.sofia",
  },
  {
    id: "alexander-master-008",
    nameEnglish: "Alexander",
    namePersian: "الکساندر",
    nameKey: "bot.name.alexander",
    rating: 2680,
    descriptionKey: "bot.description.alexander",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "بسیار محاسبه‌گر و دقیق؛ بازی‌های انتهایی قوی و توانایی برنامه‌ریزی پیچیده تاکتیکی دارد.",
    category: "Master",
    image: "/bots/master/alexander.png",
    country: "ru",
    greeting: "bot.greeting.alexander",
  },
  {
    id: "luke-master-009",
    nameEnglish: "Luke",
    namePersian: "لوک",
    nameKey: "bot.name.luke",
    rating: 2490,
    descriptionKey: "bot.description.luke",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رویکرد تهاجمی‌تر نسبت به میانگین؛ برای تمرین حملات و موقعیت‌های باز مناسب است.",
    category: "Master",
    image: "/bots/master/luke.png",
    country: "gb",
    greeting: "bot.greeting.luke",
  },
  {
    id: "wei-master-010",
    nameEnglish: "Wei",
    namePersian: "وی",
    nameKey: "bot.name.wei",
    rating: 2630,
    descriptionKey: "bot.description.wei",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "استادی سریع‌العمل با تبحر در تاکتیک‌های باز؛ مناسب تمرین تاکتیک‌های پیچیده و موقعیت‌های پویا.",
    category: "Master",
    image: "/bots/master/wei.png",
    country: "cn",
    greeting: "bot.greeting.wei",
  },
];

// ============================================================
// CHAMPIONS (2200-2700 Elo)
// ============================================================
export const CHAMPION_BOTS: Bot[] = [
  {
    id: "Aerial-Powers-BOT",
    nameEnglish: "Aerial Powers",
    namePersian: "ایریل پاورز",
    nameKey: "bot.name.Aerial-Powers-BOT",
    rating: 2500,
    descriptionEnglish: "Enjoy a friendly game of computer chess with Aerial Powers. Have a fun and engaging chess experience and see whether you can win vs. the bot.",
    descriptionPersian: "در یک بازی دوستانه شطرنج کامپیوتری با ایریال پاورز شرکت کنید. تجربه‌ای سرگرم‌کننده و جذاب از شطرنج داشته باشید و ببینید آیا می‌توانید این ربات را شکست دهید.",
    descriptionKey: "bot.description.Aerial-Powers-BOT",
    category: "Champions",
    image: "/bots/champions/aerial-powers-bot.png",
    greeting: "bot.greeting.Aerial-Powers-BOT",
  },
  {
    id: "Justin-Reid-BOT",
    nameEnglish: "Justin Reid",
    namePersian: "ژوستین رید",
    nameKey: "bot.name.Justin-Reid-BOT",
    rating: 2500,
    descriptionEnglish: "Enjoy a friendly game of computer chess with Justin Reid. Have a fun and engaging chess experience and see whether you can win vs. the bot.",
    descriptionPersian: "در یک بازی دوستانه شطرنج کامپیوتری با ژوستین رید شرکت کنید. تجربه‌ای سرگرم‌کننده و جذاب از شطرنج داشته باشید و ببینید آیا می‌توانید این ربات را شکست دهید.",
    descriptionKey: "bot.description.Justin-Reid-BOT",
    category: "Champions",
    image: "/bots/champions/justin-reid-bot.png",
    greeting: "bot.greeting.Justin-Reid-BOT",
  },
  {
    id: "JosephVottoBot",
    nameEnglish: "Joey Votto",
    namePersian: "ژوییو واتو",
    nameKey: "bot.name.JosephVottoBot",
    rating: 2500,
    descriptionEnglish: "Enjoy a friendly game of computer chess with Joey Votto. Have a fun and engaging chess experience and see whether you can win vs. the bot.",
    descriptionPersian: "در یک بازی دوستانه شطرنج کامپیوتری با ژوییو واتو شرکت کنید. تجربه‌ای سرگرم‌کننده و جذاب از شطرنج داشته باشید و ببینید آیا می‌توانید این ربات را شکست دهید.",
    descriptionKey: "bot.description.JosephVottoBot",
    category: "Champions",
    image: "/bots/champions/josephvottobot.png",
    greeting: "bot.greeting.JosephVottoBot",
  },
  {
    id: "LarryFitzgeraldBot",
    nameEnglish: "Larry Fitzgerald",
    namePersian: "لری فیتزجرالد",
    nameKey: "bot.name.LarryFitzgeraldBot",
    rating: 2500,
    descriptionEnglish: "Enjoy a friendly game of computer chess with Larry Fitzgerald. Have a fun and engaging chess experience and see whether you can win vs. the bot.",
    descriptionPersian: "در یک بازی دوستانه شطرنج کامپیوتری با لری فیتزجرالد شرکت کنید. تجربه‌ای سرگرم‌کننده و جذاب از شطرنج داشته باشید و ببینید آیا می‌توانید این ربات را شکست دهید.",
    descriptionKey: "bot.description.LarryFitzgeraldBot",
    category: "Champions",
    image: "/bots/champions/larryfitzgeraldbot.png",
    greeting: "bot.greeting.LarryFitzgeraldBot",
  },
  {
    id: "jaylen-brown",
    nameEnglish: "Jaylen Brown",
    namePersian: "جایلن براون",
    nameKey: "bot.name.jaylen-brown",
    rating: 2500,
    descriptionEnglish: "Enjoy a friendly game of computer chess with Jaylen Brown. Have a fun and engaging chess experience and see whether you can win vs. the bot.",
    descriptionPersian: "در یک بازی دوستانه شطرنج کامپیوتری با جایلن براون شرکت کنید. تجربه‌ای سرگرم‌کننده و جذاب از شطرنج داشته باشید و ببینید آیا می‌توانید این ربات را شکست دهید.",
    descriptionKey: "bot.description.jaylen-brown",
    category: "Champions",
    image: "/bots/champions/jaylen-brown.png",
    greeting: "bot.greeting.jaylen-brown",
  },
  {
    id: "Drue-Tranquill-BOT",
    nameEnglish: "Drue Tranquill",
    namePersian: "دروی ترانکويل",
    nameKey: "bot.name.Drue-Tranquill-BOT",
    rating: 2500,
    descriptionEnglish: "Enjoy a friendly game of computer chess with Drue Tranquill. Have a fun and engaging chess experience and see whether you can win vs. the bot.",
    descriptionPersian: "در یک بازی دوستانه شطرنج کامپیوتری با دروی ترانکويل شرکت کنید. تجربه‌ای سرگرم‌کننده و جذاب از شطرنج داشته باشید و ببینید آیا می‌توانید این ربات را شکست دهید.",
    descriptionKey: "bot.description.Drue-Tranquill-BOT",
    category: "Champions",
    image: "/bots/champions/drue-tranquill-bot.png",
    greeting: "bot.greeting.Drue-Tranquill-BOT",
  },
  {
    id: "GordonHaywardBot",
    nameEnglish: "Gordon Hayward",
    namePersian: "گوردون هیوارد",
    nameKey: "bot.name.GordonHaywardBot",
    rating: 2500,
    descriptionEnglish: "Enjoy a friendly game of computer chess with Gordon Hayward. Have a fun and engaging chess experience and see whether you can win vs. the bot.",
    descriptionPersian: "در یک بازی دوستانه شطرنج کامپیوتری با گوردون هیوارد شرکت کنید. تجربه‌ای سرگرم‌کننده و جذاب از شطرنج داشته باشید و ببینید آیا می‌توانید این ربات را شکست دهید.",
    descriptionKey: "bot.description.GordonHaywardBot",
    category: "Champions",
    image: "/bots/champions/gordonhaywardbot.png",
    greeting: "bot.greeting.GordonHaywardBot",
  },
  {
    id: "chidobe-awuziebot",
    nameEnglish: "Chidobe Awuzie",
    namePersian: "چیدوب آوزی",
    nameKey: "bot.name.chidobe-awuziebot",
    rating: 2500,
    descriptionEnglish: "Enjoy a friendly game of computer chess with Chidobe Awuzie. Have a fun and engaging chess experience and see whether you can win vs. the bot.",
    descriptionPersian: "در یک بازی دوستانه شطرنج کامپیوتری با چیدوب آوزی شرکت کنید. تجربه‌ای سرگرم‌کننده و جذاب از شطرنج داشته باشید و ببینید آیا می‌توانید این ربات را شکست دهید.",
    descriptionKey: "bot.description.chidobe-awuziebot",
    category: "Champions",
    image: "/bots/champions/chidobe-awuziebot.png",
    greeting: "bot.greeting.chidobe-awuziebot",
  },
  {
    id: "christian-pulisic-bot",
    nameEnglish: "Christian Pulisic",
    namePersian: "کریستین پولیسیچ",
    nameKey: "bot.name.christian-pulisic-bot",
    rating: 2500,
    descriptionEnglish: "Enjoy a friendly game of computer chess with Christian Pulisic. Have a fun and engaging chess experience and see whether you can win vs. the bot.",
    descriptionPersian: "در یک بازی دوستانه شطرنج کامپیوتری با کریستین پولیسیچ شرکت کنید. تجربه‌ای سرگرم‌کننده و جذاب از شطرنج داشته باشید و ببینید آیا می‌توانید این ربات را شکست دهید.",
    descriptionKey: "bot.description.christian-pulisic-bot",
    category: "Champions",
    image: "/bots/champions/christian-pulisic-bot.png",
    greeting: "bot.greeting.christian-pulisic-bot",
  },
  {
    id: "jaime-jaquez-jr-BOT",
    nameEnglish: "Jaime Jaquez Jr.",
    namePersian: "جامی جاکوزی جر",
    nameKey: "bot.name.jaime-jaquez-jr-BOT",
    rating: 2500,
    descriptionEnglish: "Enjoy a friendly game of computer chess with Jaime Jaquez Jr.. Have a fun and engaging chess experience and see whether you can win vs. the bot.",
    descriptionPersian: "در یک بازی دوستانه شطرنج کامپیوتری با جامی جاکوزی جر شرکت کنید. تجربه‌ای سرگرم‌کننده و جذاب از شطرنج داشته باشید و ببینید آیا می‌توانید این ربات را شکست دهید.",
    descriptionKey: "bot.description.jaime-jaquez-jr-BOT",
    category: "Champions",
    image: "/bots/champions/jaime-jaquez-jr-bot.png",
    greeting: "bot.greeting.jaime-jaquez-jr-BOT",
  },
  {
    id: "DarylMoreyBot",
    nameEnglish: "Daryl Morey",
    namePersian: "دریل موری",
    nameKey: "bot.name.DarylMoreyBot",
    rating: 2500,
    descriptionEnglish: "Enjoy a friendly game of computer chess with Daryl Morey. Have a fun and engaging chess experience and see whether you can win vs. the bot.",
    descriptionPersian: "در یک بازی دوستانه شطرنج کامپیوتری با دریلی موری شرکت کنید. تجربه‌ای سرگرم‌کننده و جذاب از شطرنج داشته باشید و ببینید آیا می‌توانید این ربات را شکست دهید.",
    descriptionKey: "bot.description.DarylMoreyBot",
    category: "Champions",
    image: "/bots/champions/darylmoreybot.png",
    greeting: "bot.greeting.DarylMoreyBot",
  },
  {
    id: "LukAIbot",
    nameEnglish: "Luk AI",
    namePersian: "لوک اِی‌آی",
    nameKey: "bot.name.LukAIbot",
    rating: 2500,
    descriptionEnglish: "Enjoy a friendly game of computer chess with Luk AI. Have a fun and engaging chess experience and see whether you can win vs. the bot.",
    descriptionPersian: "در یک بازی دوستانه شطرنج کامپیوتری با لوک اِی‌آی شرکت کنید. تجربه‌ای سرگرم‌کننده و جذاب از شطرنج داشته باشید و ببینید آیا می‌توانید این ربات را شکست دهید.",
    descriptionKey: "bot.description.LukAIbot",
    category: "Champions",
    image: "/bots/champions/lukAIbot.png",
    greeting: "bot.greeting.LukAIbot",
  },
];

// ============================================================
// MUSICIANS
// ============================================================
export const MUSICIAN_BOTS: Bot[] = [
  {
    id: "ThomasMarsBot",
    nameEnglish: "Thomas Mars",
    namePersian: "Thomas Mars",
    nameKey: "bot.thomas_mars.name",
    rating: 2000,
    descriptionEnglish: "Thomas Mars, the main singer of the French indie-pop/rap group Phoenix. Known for his melodic voice and precise melodies, a central role in the group's works and multiple artistic collaborations in contemporary music.",
    descriptionPersian: "توماس مارس، خوانندهٔ اصلی گروه ایندی-پاپ/راک فرانسوی Phoenix. شناخته‌شده برای صدای ملایم و ملودی‌های دقیق، نقش محوری در آثار گروه و همکاری‌های هنری متعدد در موسیقی معاصر.",
    descriptionKey: "bot.thomas_mars.description",
    category: "Musicians",
    image: "/bots/musicians/thomasmarsbot.png",
    country: "fr",
    greeting: "bot.thomas_mars.greeting",
  },
  {
    id: "steve-aoki-BOT",
    nameEnglish: "Steve Aoki",
    namePersian: "Steve Aoki",
    nameKey: "bot.steve_aoki.name",
    rating: 2000,
    descriptionEnglish: "Steve Aoki, the main singer of the French indie-pop/rap group Phoenix. Known for his melodic voice and precise melodies, a central role in the group's works and multiple artistic collaborations in contemporary music.",
    descriptionPersian: "استیو آوکی، دی‌جی و تهیه‌کنندهٔ موسیقی الکترونیک آمریکایی و بنیان‌گذار لیبل Dim Mak. مشهور به اجراهای پرانرژی، همکاری با هنرمندان گوناگون و رفتارهای نمایشی در سن مثل پرتاب کیک در کنسرت‌ها.",
    descriptionKey: "bot.steve_aoki.description",
    category: "Musicians",
    image: "/bots/musicians/steve-aoki-bot.png",
    country: "us",
    greeting: "bot.steve_aoki.greeting",
  },
  {
    id: "logic-BOT",
    nameEnglish: "Logic",
    namePersian: "لاجیک",
    nameKey: "bot.logic.name",
    rating: 2000,
    descriptionEnglish: "Logic, the main singer of the French indie-pop/rap group Phoenix. Known for his melodic voice and precise melodies, a central role in the group's works and multiple artistic collaborations in contemporary music.",
    descriptionPersian: "لاجیک، رپر و خوانندهٔ آمریکایی شناخته شده برای فلوهای سریع، روایت های شخصی در ترانه ها و آلبوم های پُرطرفدار که عناصر هیپ هاپ کلاسیک و معاصر را ترکیب می کنند.",
    descriptionKey: "bot.logic.description",
    category: "Musicians",
    image: "/bots/musicians/logic-bot.png",
    country: "us",
    greeting: "bot.logic.greeting",
  },
  {
    id: "wallows-BOT",
    nameEnglish: "Wallows",
    namePersian: "والوهای",
    nameKey: "bot.wallows.name",
    rating: 2000,
    descriptionEnglish: "Wallows, an indie-pop/rap group from Los Angeles, known for their melodic voice and precise melodies, a central role in the group's works and multiple artistic collaborations in contemporary music.",
    descriptionPersian: "والوهای، گروه ایندی راک/پاپ آمریکایی از لس-آنجلس، شناخته شده برای آهنگ های ملودیک، فضاسازی نوستالژیک و حضور باثبات در صحنه موسیقی مستقل معاصر.",
    descriptionKey: "bot.wallows.description",
    category: "Musicians",
    image: "/bots/musicians/wallows-bot.png",
    country: "us",
    greeting: "bot.wallows.greeting",
  },
];

// ============================================================
// TOP PLAYERS (Historical/Famous)
// ============================================================
export const TOP_PLAYER_BOTS: Bot[] = [
  {
    id: "Hikaru-bot",
    nameEnglish: "Hikaru Nakamura",
    namePersian: "هیکارو ناکامورا",
    nameKey: "bot.hikaru.name",
    rating: 2775,
    descriptionEnglish: "Hikaru Nakamura, a US grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "هیکارو ناکامورا، استاد بزرگ (GM) آمریکایی، متخصص شطرنج سریع و بلیتس؛ شناخته شده برای سبک تهاجمی و حضور گسترده در بازی های آنلاین. (رتبه عددی تقریباً نشان دهنده توانایی بات است.)",
    descriptionKey: "bot.hikaru.description",
    category: "TopPlayers",
    image: "/bots/top_players/Hikaru-bot.png",
    country: "us",
    greeting: "bot.hikaru.greeting",
    cardStyle: "golden",
  },
  {
    id: "AnnaMuzychukBot",
    nameEnglish: "Anna Muzychuk",
    namePersian: "آنا موزیچوک",
    nameKey: "bot.annamuzychuk.name",
    rating: 2550,
    descriptionEnglish: "Anna Muzychuk, a Ukrainian women's grandmaster (WGM/GM), a quick chess player and blitz specialist; known for her aggressive style and extensive presence in online games.",
    descriptionPersian: "آنا موزیچوک، استاد بزرگ زنی (WGM/GM) اوکراینی، قهرمان مسابقات قهرمانی زنان در کنترل سریع؛ شناخته شده برای تسلط در مراحل میانی بازی و آمادگی مسابقاتی. (رتبه عددی تقریباً نشان دهنده توانایی بات است.)",
    descriptionKey: "bot.annamuzychuk.description",
    category: "TopPlayers",
    image: "/bots/top_players/AnnaMuzychukBot.png",
    country: "ua",
    greeting: "bot.annamuzychuk.greeting",
  },
  {
    id: "Vishy-Bot",
    nameEnglish: "Vishy Anand",
    namePersian: "ویشی اناند",
    nameKey: "bot.vishy.name",
    rating: 2755,
    descriptionEnglish: "Vishy Anand, an Indian grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "ویشواناثان (ویشی) اناند، استاد بزرگ هندی و قهرمان سابق جهان؛ بات نماینده سبک عمیق و تجربه بالای مسابقاتی است. (رتبه عددی تقریباً نشان دهنده توانایی بات است.)",
    descriptionKey: "bot.vishy.description",
    category: "TopPlayers",
    image: "/bots/top_players/Vishy-Bot.png",
    country: "in",
    greeting: "bot.vishy.greeting",
  },
  {
    id: "DingLirenBot",
    nameEnglish: "Ding Liren",
    namePersian: "دینگ لیرن",
    nameKey: "bot.dingliren.name",
    rating: 2790,
    descriptionEnglish: "Ding Liren, a Chinese grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "دینگ لیرن، استاد بزرگ چینی و قهرمان سابق جهان؛ بات نماینده سبک عمیق و تجربه بالای مسابقاتی است. (رتبه عددی تقریباً نشان دهنده توانایی بات است.)",
    descriptionKey: "bot.dingliren.description",
    category: "TopPlayers",
    image: "/bots/top_players/DingLirenBot.png",
    country: "cn",
    greeting: "bot.dingliren.greeting",
  },
  {
    id: "Caruanabot",
    nameEnglish: "Fabiano Caruana",
    namePersian: "فابیانو کاروآنا",
    nameKey: "bot.caruanabot.name",
    rating: 2815,
    descriptionEnglish: "Fabiano Caruana, an American grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "فابیانو کاروآنا، استاد بزرگ آمریکایی (اصل ایتالیایی/ایتالیا‌زادهٔ ایتالیا/اکنون در آمریکا بازی می‌کند)، شناخته شده برای بازی‌های فنی و آمادگی بالای بازکردن؛ باتی با سطح قوی محاسباتی.",
    descriptionKey: "bot.caruanabot.description",
    category: "TopPlayers",
    image: "/bots/top_players/Caruanabot.png",
    country: "us",
    greeting: "bot.caruanabot.greeting",
    cardStyle: "golden",
  },
  {
    id: "Kosteniuk-Bot",
    nameEnglish: "Alina Kosteniuk",
    namePersian: "کاستنیوک",
    nameKey: "bot.kosteniuk.name",
    rating: 2520,
    descriptionEnglish: "Alina Kosteniuk, a Russian women's grandmaster (WGM/GM), a quick chess player and blitz specialist; known for her aggressive style and extensive presence in online games.",
    descriptionPersian: "الکساندرا کاستنیوک — استاد بزرگ زن روسی و قهرمان سابق زنان جهان؛ بات نمایانگر تجربهٔ تهاجمی و دانش عمیق خط‌های نظری است. ",
    descriptionKey: "bot.kosteniuk.description",
    category: "TopPlayers",
    image: "/bots/top_players/Kosteniuk-Bot.png",
    country: "ru",
    greeting: "bot.kosteniuk.greeting",
  },
  {
    id: "Naroditsky-Bot",
    nameEnglish: "Naroditsky",
    namePersian: "دانیا",
    nameKey: "bot.naroditsky.name",
    rating: 2620,
    descriptionEnglish: "Naroditsky, an American grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "دنیل نارودیتسکی — استاد بزرگ آمریکایی، استاد و محتواساز شطرنج، شناخته شده برای بازی های خلاقانه و آموزشی. ",
    descriptionKey: "bot.naroditsky.description",
    category: "TopPlayers",
    image: "/bots/top_players/Naroditsky-Bot.png",
    country: "us",
    greeting: "bot.naroditsky.greeting",
  },
  {
    id: "NepomniachtchiBot",
    nameEnglish: "Nepomniachtchi",
    namePersian: "ایان",
    nameKey: "bot.nepomniachtchi.name",
    rating: 2745,
    descriptionEnglish: "Nepomniachtchi, a Russian grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "یان لپونیاچی (نِپو) — استاد بزرگ روسی، شناخته شده برای بازی سریع و محاسبات قوی در موقعیت‌های پیچیده. )",
    descriptionKey: "bot.nepomniachtchi.description",
    category: "TopPlayers",
    image: "/bots/top_players/NepomniachtchiBot.png",
    country: "ru",
    greeting: "bot.nepomniachtchi.greeting",
  },
  {
    id: "AronianBot1",
    nameEnglish: "Aronian",
    namePersian: "آرونیان",
    nameKey: "bot.aronian.name",
    rating: 2760,
    descriptionEnglish: "Aronian, a Russian grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "لوون آرونیان — استاد بزرگ با سبک خلاق و تهاجمی؛ نمایندهٔ یکی از برجسته‌ترین شطرنج‌بازان معاصر. )",
    descriptionKey: "bot.aronian.description",
    category: "TopPlayers",
    image: "/bots/top_players/AronianBot1.png",
    country: "am",
    greeting: "bot.aronian.greeting",
  },
  {
    id: "paulmorphy-BOT",
    nameEnglish: "Paul Morphy",
    namePersian: "پل مورفی",
    nameKey: "bot.paulmorphy.name",
    rating: 2600,
    descriptionEnglish: "Paul Morphy, an American grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "پل مورفی — استاد تاریخی آمریکایی سدهٔ ۱۹، از پیشگامان شطرنج مدرن. (رتبهٔ عددی ذکرشده تقریب تاریخی برای نمایندگی توانایی بات است؛ طبیعتاً مقایسهٔ مستقیم با ریتینگ‌های مدرن پیچیده است.)",
    descriptionKey: "bot.paulmorphy.description",
    category: "TopPlayers",
    image: "/bots/top_players/paulmorphy-BOT.png",
    country: "us",
    greeting: "bot.paulmorphy.greeting",
  },
  {
    id: "JuditPolgarBot",
    nameEnglish: "Judit Polgar",
    namePersian: "جودیت پولگار",
    nameKey: "bot.juditpolgar.name",
    rating: 2735,
    descriptionEnglish: "Judit Polgar, a Hungarian grandmaster (GM), a quick chess player and blitz specialist; known for her aggressive style and extensive presence in online games.",
    descriptionPersian: "جودیت پولگار — استاد بزرگ مجارستانی، یکی از قوی‌ترین زنان تاریخ شطرنج که به‌طور مداوم در برابر بهترین‌های جهان بازی کرده است. )",
    descriptionKey: "bot.juditpolgar.description",
    category: "TopPlayers",
    image: "/bots/top_players/JuditPolgarBot.png",
    country: "hu",
    greeting: "bot.juditpolgar.greeting",
  },
  {
    id: "viditbot",
    nameEnglish: "Vidit",
    namePersian: "ویدیت",
    nameKey: "bot.vidit.name",
    rating: 2710,
    descriptionEnglish: "Vidit, an Indian grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "ویدیت گرگِرِسِن — استاد بزرگ هندی، شناخته شده برای بازی های محاسباتی دقیق و سبک قابل اعتماد در رقابت های سطح بالا. )",
    descriptionKey: "bot.vidit.description",
    category: "TopPlayers",
    image: "/bots/top_players/viditbot.png",
    country: "in",
    greeting: "bot.vidit.greeting",
  },
  {
    id: "IrinaKrushBot",
    nameEnglish: "Irina Krush",
    namePersian: "ایرینا کراش",
    nameKey: "bot.irinakrush.name",
    rating: 2450,
    descriptionEnglish: "Irina Krush, an American grandmaster (GM), a quick chess player and blitz specialist; known for her aggressive style and extensive presence in online games.",
    descriptionPersian: "ایرینا کراش — استاد بزرگ زن آمریکایی، چندبار قهرمان ملی آمریکا؛ باتی آموزشی و رقابتی با تجربهٔ گستردهٔ تورنمنت. )",
    descriptionKey: "bot.irinakrush.description",
    category: "TopPlayers",
    image: "/bots/top_players/IrinaKrushBot.png",
    country: "us",
    greeting: "bot.irinakrush.greeting",
  },
  {
    id: "Giri-Bot",
    nameEnglish: "Giri",
    namePersian: "گیری",
    nameKey: "bot.giri.name",
    rating: 2770,
    descriptionEnglish: "Giri, an Indonesian grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "آنیش گیری — استاد بزرگ هلندی، شناخته شده برای بازی فنی و تسلط نظریهٔ افتتاحیه؛ بات نمایندهٔ سطح بسیار بالا. )",
    descriptionKey: "bot.giri.description",
    category: "TopPlayers",
    image: "/bots/top_players/Giri-Bot.png",
    country: "nl",
    greeting: "bot.giri.greeting",
  },
  {
    id: "Abdusattorov-Bot",
    nameEnglish: "Abdusattorov",
    namePersian: "عبدالستارف",
    nameKey: "bot.abdusattorov.name",
    rating: 2730,
    descriptionEnglish: "Abdusattorov, an Uzbek grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "رفات عبدالستّروف — استاد بزرگ ازبکستان، قهرمان جوان و تهاجمی معاصر؛ بات نمایانگر سبک سریع و قدرتمند جوانان. )",
    descriptionKey: "bot.abdusattorov.description",
    category: "TopPlayers",
    image: "/bots/top_players/Abdusattorov-Bot.png",
    country: "uz",
    greeting: "bot.abdusattorov.greeting",
  },
  {
    id: "lasker-BOT",
    nameEnglish: "Lasker",
    namePersian: "لاسکر",
    nameKey: "bot.lasker.name",
    rating: 2580,
    descriptionEnglish: "Lasker, an American grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "اِمانوئل لاسکر — استاد بزرگ تاریخی آلمانی، قهرمان جهان آغاز سدهٔ ۲۰؛ این بات نمایانگر سبک کلاسیک و قواعد تاریخی شطرنج است. (رتبهٔ عددی تقریب تاریخی است.)",
    descriptionKey: "bot.lasker.description",
    category: "TopPlayers",
    image: "/bots/top_players/lasker-BOT.png",
    country: "de",
    greeting: "bot.lasker.greeting",
  },
  {
    id: "HouYifanBot",
    nameEnglish: "Hou Yifan",
    namePersian: "هو یی‌فان",
    nameKey: "bot.houyifan.name",
    rating: 2650,
    descriptionEnglish: "Hou Yifan, a Chinese grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "هو یی‌فان — استاد بزرگ زن چینی و از بارزترین چهره‌های شطرنج زنان معاصر؛ باتی با پایهٔ قوی نظری و تاکتیکی. )",
    descriptionKey: "bot.houyifan.description",
    category: "TopPlayers",
    image: "/bots/top_players/HouYifanBot.png",
    country: "cn",
    greeting: "bot.houyifan.greeting",
  },
  {
    id: "bokbot",
    nameEnglish: "Bok",
    namePersian: "بوک",
    nameKey: "bot.bok.name",
    rating: 2500,
    descriptionEnglish: "Bok, a Chinese grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "بوک — بات نمایندهٔ بازیکنی به‌نام 'بوک'؛ توضیحات و منشأ دقیق‌تر بستگی به مرجع داخلی پلتفرم دارد. (رتبهٔ تقریبی برای نمایندگی توانایی بات ذکر شده.)",
    descriptionKey: "bot.bok.description",
    category: "TopPlayers",
    image: "/bots/top_players/bokbot.png",
    country: undefined,
    greeting: "bot.bok.greeting",
  },
  {
    id: "wesleysobot",
    nameEnglish: "Wesley So",
    namePersian: "وسلی سو",
    nameKey: "bot.wesleyso.name",
    rating: 2770,
    descriptionEnglish: "Wesley So, an Indonesian grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "وسلی سو — استاد بزرگ آمریکایی (اصل فیلیپینی) و بازیکن رده‌بالا؛ باتی با سبک فنی و آمادهٔ رقابت در سطوح بالا. )",
    descriptionKey: "bot.wesleyso.description",
    category: "TopPlayers",
    image: "/bots/top_players/wesleysobot.png",
    country: "us",
    greeting: "bot.wesleyso.greeting",
  },
  {
    id: "tal-BOT",
    nameEnglish: "Michael Tal",
    namePersian: "تال",
    nameKey: "bot.tal.name",
    rating: 2650,
    descriptionEnglish: "Michael Tal, an Indonesian grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "میکائیل تال — استاد بزرگ تاریخی لاتویایی (شهروند سابق اتحاد شوروی) معروف به بازی‌های بسیار تهاجمی و تاکتیکی؛ این بات نمایانگر سبک تهاجمی کلاسیک او است. )",
    descriptionKey: "bot.tal.description",
    category: "TopPlayers",
    image: "/bots/top_players/tal-BOT.png",
    country: "lv",
    greeting: "bot.tal.greeting",
  },
  {
    id: "capablanca-BOT",
    nameEnglish: "Capablanca",
    namePersian: "کاپابلانکا",
    nameKey: "bot.capablanca.name",
    rating: 2680,
    descriptionEnglish: "Capablanca, an Indonesian grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "خوسه رائول کاپابلانکا — استاد بزرگ تاریخی کوبایی و قهرمان جهان اوایل سدهٔ ۲۰؛ بات نمایانگر بازی کلاسیک و فنی او است. )",
    descriptionKey: "bot.capablanca.description",
    category: "TopPlayers",
    image: "/bots/top_players/capablanca-BOT.png",
    country: "cu",
    greeting: "bot.capablanca.greeting",
  },
  {
    id: "world-champion-carlsen",
    nameEnglish: "Magnus Carlsen",
    namePersian: "مگنوس",
    nameKey: "bot.carlsen.name",
    rating: 2882,
    descriptionEnglish: "Magnus Carlsen, a Norwegian grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games.",
    descriptionPersian: "مگنوس کارلسن — استاد بزرگ نروژی و قهرمان جهان؛ یکی از قدرتمندترین بازیکنان تاریخ معاصر که بات نمایانگر سبک همه‌جانبه و درک موقعیتی عمیق او است. )",
    descriptionKey: "bot.carlsen.description",
    category: "TopPlayers",
    image: "/bots/top_players/world-champion-carlsen.png",
    country: "no",
    greeting: "bot.carlsen.greeting",
    cardStyle: "golden",
  },
  {
    id: "firouzja-bot",
    nameEnglish: "Firouzja",
    namePersian: "علیرضا فیروزجا",
    nameKey: "bot.firouzja.name",
    rating: 2804,
    descriptionEnglish: "Firouzja, an Iranian grandmaster (GM), a quick chess player and blitz specialist; known for his aggressive style and extensive presence in online games. ",
    descriptionPersian: "نابغه شطرنج متولد ۱۳۸۲ ایران، ساکن فرانسه؛ جوان‌ترین بازیکن تاریخ با ریتینگ بالای ۲۸۰۰ و مدعی جدی قهرمانی جهان.",
    descriptionKey: "bot.firouzja.description",
    category: "TopPlayers",
    image: "/bots/top_players/firouzjaBot.png",
    country: ["fr", "ir"],
    greeting: "bot.firouzja.greeting",
    cardStyle: "golden",
  },
];

// ============================================================
// ENGINE CATEGORY (Under Development)
// ============================================================
export const ENGINE_BOTS: Bot[] = [];

// ============================================================
// HELPER FUNCTIONS
// ============================================================

/**
 * Get all bots from all categories
 */
export function getAllBots(): Bot[] {
  return [
    ...BEGINNER_BOTS,
    ...INTERMEDIATE_BOTS,
    ...ADVANCED_BOTS,
    ...MASTER_BOTS,
    ...CHAMPION_BOTS,
    ...MUSICIAN_BOTS,
    ...TOP_PLAYER_BOTS,
    ...ENGINE_BOTS,
  ];
}

/**
 * Get bots filtered by category
 */
export function getBotsByCategory(category: BotCategory): Bot[] {
  switch (category) {
    case "Beginner":
      return BEGINNER_BOTS;
    case "Intermediate":
      return INTERMEDIATE_BOTS;
    case "Advanced":
      return ADVANCED_BOTS;
    case "Master":
      return MASTER_BOTS;
    case "Champions":
      return CHAMPION_BOTS;
    case "Musicians":
      return MUSICIAN_BOTS;
    case "TopPlayers":
      return TOP_PLAYER_BOTS;
    case "Engine":
      return ENGINE_BOTS;
    default:
      return [];
  }
}

/**
 * Get a specific bot by ID
 */
export function getBotById(id: string): Bot | undefined {
  return getAllBots().find((bot) => bot.id === id);
}

/**
 * Create a custom bot with specified rating
 */
export function createCustomBot(name: string, rating: number): Bot {
  return {
    id: `custom-${Date.now()}`,
    nameEnglish: name,
    namePersian: name,
    nameKey: "",
    rating: Math.max(200, Math.min(3500, rating)),
    descriptionEnglish: `Custom bot with ${rating} Elo`,
    descriptionPersian: `Custom bot with ${rating} Elo`,
    descriptionKey: "",
    category: "Custom",
  };
}
