// Bot data types and predefined bots
// Easy to add new bots - just add to the appropriate category array

export interface BotPersonality {
  chatFrequency: "low" | "medium" | "high";
  playStyle: "defensive" | "balanced" | "aggressive";
  blunderReaction: string; // key relative to bot prefix
  winReaction: string;
  lossReaction: string;
}

export interface Bot {
  id: string;
  nameKey: string; // Translation key for bot name
  nameEnglish: string; // English name
  namePersian: string; // Persian name
  rating: number;
  descriptionKey: string; // Translation key for description
  descriptionEnglish: string; // English description
  descriptionPersian: string; // Persian description
  category: BotCategory;
  image?: string; // Path to bot image
  country?: string | string[]; // Country code(s) for flag (e.g., "us", "ru", or ["fr", "ir"])
  greeting?: string; // Custom greeting translation key
  cardStyle?: CardStyle; // Special card appearance style
  youtubeUrl?: string; // YouTube channel URL for creators

  // New fields for advanced engine personalization
  personality?: Partial<BotPersonality>;
  openingPreferences?: string[]; // e.g. ["e2e4", "g1f3"]
}

export type CardStyle = "golden" | "youtube";

export type BotCategory =
  | "Beginner"
  | "Intermediate"
  | "Advanced"
  | "Master"
  | "PersianCreators"
  | "Champions"
  | "Musicians"
  | "TopPlayers"
  | "Engine"
  | "Custom";

export const BOT_CATEGORIES: BotCategory[] = [
  "Beginner",
  "Intermediate",
  "Advanced",
  "Master",
  "PersianCreators",
  "Champions",
  "Musicians",
  "TopPlayers",
  "Engine",
];

// ============================================================
// BEGINNER BOTS (200-600 Elo)
// ============================================================
export const BEGINNER_BOTS: Bot[] = [
  {
    id: "martin",
    nameKey: "Bots.Bot.Martin.Name",
    nameEnglish: "Martin",
    namePersian: "مارتین",
    rating: 250,
    descriptionKey: "Bots.Bot.Martin.Desc",
    descriptionEnglish: "A friendly beginner bot that has just learned the rules.",
    descriptionPersian: "ربات مبتدی دوستانه که تازه قوانین را یاد گرفته است.",
    category: "Beginner",
    image: "/bots/beginner/martin.png",
    personality: {
      chatFrequency: "high",
      playStyle: "balanced",
      blunderReaction: "oops",
      winReaction: "yay",
      lossReaction: "gg",
    }
  },
  {
    id: "wayne",
    nameKey: "Bots.Bot.Wayne.Name",
    nameEnglish: "Wayne",
    namePersian: "وین",
    rating: 428,
    descriptionKey: "Bots.Bot.Wayne.Desc",
    descriptionEnglish: "A beginner bot that makes simple moves.",
    descriptionPersian: "ربات مبتدی که حرکت‌های ساده انجام می‌دهد.",
    category: "Beginner",
    image: "/bots/beginner/wayne.png",
  },
  {
    id: "fabian",
    nameKey: "Bots.Bot.Fabian.Name",
    nameEnglish: "Fabian",
    namePersian: "فابیان",
    rating: 457,
    descriptionKey: "Bots.Bot.Fabian.Desc",
    descriptionEnglish: "A beginner bot with basic strategies.",
    descriptionPersian: "ربات مبتدی با استراتژی‌های پایه.",
    category: "Beginner",
    image: "/bots/beginner/fabian.png",
  },
  {
    id: "juan",
    nameEnglish: "Juan",
    namePersian: "جان",
    nameKey: "Bots.Bot.Juan.Name",
    rating: 485,
    descriptionKey: "Bots.Bot.Juan.Desc",
    descriptionEnglish: "A beginner bot that learns simple tactical patterns.",
    descriptionPersian: "ربات مبتدی که الگوهای تاکتیکی ساده را یاد می‌گیرد.",
    category: "Beginner",
    image: "/bots/beginner/juan.png",
  },
  {
    id: "filip",
    nameEnglish: "Filip",
    namePersian: "فیلیپ",
    nameKey: "Bots.Bot.Filip.Name",
    rating: 514,
    descriptionKey: "Bots.Bot.Filip.Desc",
    descriptionEnglish: "A beginner bot with calm and steady moves.",
    descriptionPersian: "ربات مبتدی با حرکت‌های آرام و ثابت.",
    category: "Beginner",
    image: "/bots/beginner/filip.png",
  },
  {
    id: "elani",
    nameEnglish: "Elani",
    namePersian: "الانی",
    nameKey: "Bots.Bot.Elani.Name",
    rating: 543,
    descriptionKey: "Bots.Bot.Elani.Desc",
    descriptionEnglish: "A beginner bot that is a member of the chess club.",
    descriptionPersian: "ربات مبتدی عضو باشگاه شطرنج مدرسه.",
    category: "Beginner",
    image: "/bots/beginner/elani.png",
  },
  {
    id: "noel",
    nameEnglish: "Noel",
    namePersian: "نوئل",
    nameKey: "Bots.Bot.Noel.Name",
    rating: 571,
    descriptionKey: "Bots.Bot.Noel.Desc",
    descriptionEnglish: "A beginner bot that is a chess enthusiast who learns tactical patterns.",
    descriptionPersian: "ربات مبتدی کنجکاو که الگوهای تاکتیکی را یاد می‌گیرد.",
    category: "Beginner",
    image: "/bots/beginner/noel.png",
  },
  {
    id: "oliver",
    nameEnglish: "Oliver",
    namePersian: "اولیور",
    nameKey: "Bots.Bot.Oliver.Name",
    rating: 600,
    descriptionKey: "Bots.Bot.Oliver.Desc",
    descriptionEnglish: "A beginner bot with basic knowledge.",
    descriptionPersian: "ربات مبتدی با دانش پایه.",
    category: "Beginner",
    image: "/bots/beginner/oliver.png",
  },
  {
    id: "milica",
    nameEnglish: "Milica",
    namePersian: "میلیکا",
    nameKey: "Bots.Bot.Milica.Name",
    rating: 628,
    descriptionKey: "Bots.Bot.Milica.Desc",
    descriptionEnglish: "A beginner bot that likes simple moves.",
    descriptionPersian: "ربات مبتدی که حرکت‌های ساده دوست دارد.",
    category: "Beginner",
    image: "/bots/beginner/milica.png",
  },
  {
    id: "aron",
    nameEnglish: "Aron",
    namePersian: "آرون",
    nameKey: "Bots.Bot.Aron.Name",
    rating: 657,
    descriptionKey: "Bots.Bot.Aron.Desc",
    descriptionEnglish: "A beginner bot with basic strategies.",
    descriptionPersian: "ربات مبتدی با استراتژی‌های ابتدایی.",
    category: "Beginner",
    image: "/bots/beginner/aron.png",
  },
  {
    id: "janjay",
    nameEnglish: "Janjay",
    namePersian: "جانجای",
    nameKey: "Bots.Bot.Janjay.Name",
    rating: 685,
    descriptionKey: "Bots.Bot.Janjay.Desc",
    descriptionEnglish: "A friendly beginner bot.",
    descriptionPersian: "ربات مبتدی دوستانه.",
    category: "Beginner",
    image: "/bots/beginner/janjay.png",
  },
  {
    id: "mina",
    nameEnglish: "Mina",
    namePersian: "مینا",
    nameKey: "Bots.Bot.Mina.Name",
    rating: 714,
    descriptionKey: "Bots.Bot.Mina.Desc",
    descriptionEnglish: "A beginner bot that learns the rules.",
    descriptionPersian: "ربات مبتدی که قوانین را یاد می‌گیرد.",
    category: "Beginner",
    image: "/bots/beginner/mina.png",
  },
  {
    id: "zara",
    nameEnglish: "Zara",
    namePersian: "زارا",
    nameKey: "Bots.Bot.Zara.Name",
    rating: 743,
    descriptionKey: "Bots.Bot.Zara.Desc",
    descriptionEnglish: "A beginner bot with basic moves.",
    descriptionPersian: "ربات مبتدی با حرکت‌های پایه.",
    category: "Beginner",
    image: "/bots/beginner/zara.png",
  },
  {
    id: "santiago",
    nameEnglish: "Santiago",
    namePersian: "سانتیاگو",
    nameKey: "Bots.Bot.Santiago.Name",
    rating: 771,
    descriptionKey: "Bots.Bot.Santiago.Desc",
    descriptionEnglish: "A beginner bot that is a chess enthusiast.",
    descriptionPersian: "ربات مبتدی کنجکاو.",
    category: "Beginner",
    image: "/bots/beginner/santiago.png",
  },
  {
    id: "karim",
    nameEnglish: "Karim",
    namePersian: "کریم",
    nameKey: "Bots.Bot.Karim.Name",
    rating: 800,
    descriptionKey: "Bots.Bot.Karim.Desc",
    descriptionEnglish: "A beginner bot with basic chess knowledge.",
    descriptionPersian: "ربات مبتدی با دانش پایه شطرنج.",
    category: "Beginner",
    image: "/bots/beginner/karim.png",
  },
];

// ============================================================
// INTERMEDIATE BOTS (800-1200 Elo)
// ============================================================
export const INTERMEDIATE_BOTS: Bot[] = [
  {
    id: "Maria-Bot",
    nameEnglish: "Maria",
    namePersian: "ماریا",
    nameKey: "bot.name.maria",
    rating: 1500,
    descriptionKey: "bot.description.maria",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/maria.png",
  },
  {
    id: "Maxim-Bot",
    nameEnglish: "Maxim",
    namePersian: "ماکسیم",
    nameKey: "bot.name.maxim",
    rating: 1500,
    descriptionKey: "bot.description.maxim",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/maxim.png",
  },
  {
    id: "Hans-Bot",
    nameEnglish: "Hans",
    namePersian: "هانس",
    nameKey: "bot.name.hans",
    rating: 1500,
    descriptionKey: "bot.description.hans",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/hans.png",
  },
  {
    id: "Azeez-Bot",
    nameEnglish: "Azeez",
    namePersian: "عزیز",
    nameKey: "bot.name.azeez",
    rating: 1500,
    descriptionKey: "bot.description.azeez",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/azeez.png",
  },
  {
    id: "Laura-Bot",
    nameEnglish: "Laura",
    namePersian: "لورا",
    nameKey: "bot.name.laura",
    rating: 1500,
    descriptionKey: "bot.description.laura",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/laura.png",
  },
  {
    id: "Sven-Bot",
    nameEnglish: "Sven",
    namePersian: "سون",
    nameKey: "bot.name.sven",
    rating: 1500,
    descriptionKey: "bot.description.sven",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/sven.png",
  },
  {
    id: "Emir-Bot",
    nameEnglish: "Emir",
    namePersian: "امیر",
    nameKey: "bot.name.emir",
    rating: 1500,
    descriptionKey: "bot.description.emir",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/emir.png",
  },
  {
    id: "Elena-Bot",
    nameEnglish: "Elena",
    namePersian: "النا",
    nameKey: "bot.name.elena",
    rating: 1500,
    descriptionKey: "bot.description.elena",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/elena.png",
  },
  {
    id: "Wilson-Bot",
    nameEnglish: "Wilson",
    namePersian: "ویلسون",
    nameKey: "bot.name.wilson",
    rating: 1500,
    descriptionKey: "bot.description.wilson",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/wilson.png",
  },
  {
    id: "Vinh-Bot",
    nameEnglish: "Vinh",
    namePersian: "وین",
    nameKey: "bot.name.vinh",
    rating: 1500,
    descriptionKey: "bot.description.vinh",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/vinh.png",
  },
  {
    id: "Nelson-Bot",
    nameEnglish: "Nelson",
    namePersian: "نلسون",
    nameKey: "bot.name.nelson",
    rating: 1500,
    descriptionKey: "bot.description.nelson",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/nelson.png",
  },
  {
    id: "Jade-Bot",
    nameEnglish: "Jade",
    namePersian: "جِید",
    nameKey: "bot.name.jade",
    rating: 1500,
    descriptionKey: "bot.description.jade",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/jade.png",
  },
  {
    id: "David-Bot",
    nameEnglish: "David",
    namePersian: "دیوید",
    nameKey: "bot.name.david",
    rating: 1500,
    descriptionKey: "bot.description.david",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/david.png",
  },
  {
    id: "Ali-Bot",
    nameEnglish: "Ali",
    namePersian: "علی",
    nameKey: "bot.name.ali",
    rating: 1500,
    descriptionKey: "bot.description.ali",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/ali.png",
  },
  {
    id: "Mateo-Bot",
    nameEnglish: "Mateo",
    namePersian: "متیو",
    nameKey: "bot.name.mateo",
    rating: 1500,
    descriptionKey: "bot.description.mateo",
    descriptionEnglish: "An intermediate bot with basic chess knowledge.",
    descriptionPersian: "ربات با سطح متوسط با دانش پایه شطرنج.",
    category: "Intermediate",
    image: "/bots/intermediate/mateo.png",
  },
];

// ============================================================
// ADVANCED BOTS (1200-1600 Elo)
// ============================================================
export const ADVANCED_BOTS: Bot[] = [
  {
    id: "wendy-bot",
    nameEnglish: "Wendy",
    namePersian: "وندی",
    nameKey: "bot.name.wendy",
    rating: 1750,
    descriptionKey: "bot.description.wendy",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی پیشرفته با گرایش تهاجمی و توان بالا در تاکتیک‌های موقعیتی؛ مناسب برای بازیکنان میانه‌تاپیشرفته که دنبال تمرین محاسبات تاکتیکی هستند.",
    category: "Advanced",
    image: "/bots/advanced/wendy.png",
    greeting: "bot.greeting.wendy",
  },
  {
    id: "Antonio-Bot",
    nameEnglish: "Antonio",
    namePersian: "آنتونیو",
    nameKey: "bot.name.antonio",
    rating: 1850,
    descriptionKey: "bot.description.antonio",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی با سبک بازی متعادل و استحکام موقعیتی؛ کمتر ریسک‌پذیر و مناسب برای تمرین خط‌مشی‌های پوزیسیونی.",
    category: "Advanced",
    image: "/bots/advanced/antonio.png",
    country: "es",
    greeting: "bot.greeting.antonio",
  },
  {
    id: "Pierre-Bot",
    nameEnglish: "Pierre",
    namePersian: "پیر",
    nameKey: "bot.name.pierre",
    rating: 1900,
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی تکنیکی و محاسباتی که به برنامه‌ریزی بلندمدت و اجرای طرح‌های میانه‌بازی توجه دارد؛ مناسب برای تمرین بازی موقعیتی و انتهای بازی.",
    descriptionKey: "bot.description.pierre",
    category: "Advanced",
    image: "/bots/advanced/pierre.png",
    country: "fr",
    greeting: "bot.greeting.pierre",
  },
  {
    id: "Pablo-Bot",
    nameEnglish: "Pablo",
    namePersian: "پابلو",
    nameKey: "bot.name.pablo",
    rating: 1700,
    descriptionKey: "bot.description.pablo",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی هجومی-تاکتیکی که در موقعیت‌های باز بسیار خطرناک است؛ برای تمرین حمله و محاسبات ترکیبی مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/pablo.png",
    country: "es",
    greeting: "bot.greeting.pablo",
  },
  {
    id: "Joel-Bot",
    nameEnglish: "Joel",
    namePersian: "جول",
    nameKey: "bot.name.joel",
    rating: 1800,
    descriptionKey: "bot.description.joel",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی با سبک همه‌کاره که تعادل خوبی بین تاکتیک و پوزیسیون دارد؛ گزینه‌ای مناسب برای بازیکنانی که می‌خواهند جنبه‌های مختلف بازی را تمرین کنند.",
    category: "Advanced",
    image: "/bots/advanced/joel.png",
    greeting: "bot.greeting.joel",
  },
  {
    id: "Isabel-Bot",
    nameEnglish: "Isabel",
    namePersian: "ایزابل",
    nameKey: "bot.name.isabel",
    rating: 1950,
    descriptionKey: "bot.description.isabel",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی با دقت بالا در محاسبات و تسلط بر انتهای بازی؛ برای تمرین تبدیل مزیت به پیروزی و مطالعه انتهای بازی مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/isabel.png",
    country: "es",
    greeting: "bot.greeting.isabel",
  },
  {
    id: "Arthur-Bot",
    nameEnglish: "Arthur",
    namePersian: "آرتور",
    nameKey: "bot.name.arthur",
    rating: 2000,
    descriptionKey: "bot.description.arthur",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی کلاسیک و ساخت‌یافته که به اصول بنیادین شطرنج پایبند است؛ مناسب برای آشنایی با خطوط اصلی و استراتژی‌های کلاسیک.",
    category: "Advanced",
    image: "/bots/advanced/arthur.png",
    country: "gb",
    greeting: "bot.greeting.arthur",
  },
  {
    id: "Jonas-Bot",
    nameEnglish: "Jonas",
    namePersian: "جوناس",
    nameKey: "bot.name.jonas",
    rating: 1780,
    descriptionKey: "bot.description.jonas",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی منعطف که بین بازی حفاظتی و هجومی تغییر سبک می‌دهد؛ برای بررسی پاسخ‌های مختلف به گشایش‌های متنوع مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/jonas.png",
    country: "se",
    greeting: "bot.greeting.jonas",
  },
  {
    id: "Isla-Bot",
    nameEnglish: "Isla",
    namePersian: "ایسلا",
    nameKey: "bot.name.isla",
    rating: 1670,
    descriptionKey: "bot.description.isla",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی که تمایل به بازی باز و پویایی دارد؛ مناسب برای تمرین بازی‌های تاکتیکی و تمرکز بر محاسبات کوتاه‌مدت.",
    category: "Advanced",
    image: "/bots/advanced/isla.png",
    greeting: "bot.greeting.isla",
  },
  {
    id: "Lorenzo-Bot",
    nameEnglish: "Lorenzo",
    namePersian: "لورنزو",
    nameKey: "bot.name.lorenzo",
    rating: 1820,
    descriptionKey: "bot.description.lorenzo",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی با تاکید بر بازی موقعیتی و مدیریت ساختار پیاده؛ برای تمرین برنامه‌ریزی میانه‌بازی مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/lorenzo.png",
    country: "it",
    greeting: "bot.greeting.lorenzo",
  },
  {
    id: "Wally-Bot",
    nameEnglish: "Wally",
    namePersian: "والی",
    nameKey: "bot.name.wally",
    rating: 1600,
    descriptionKey: "bot.description.wally",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی نسبتاً سازگار برای تمرین بازیکنانی که می‌خواهند در برابر بازی‌های غیرمنتظره و اشتباهات حریف تمرین کنند.",
    category: "Advanced",
    image: "/bots/advanced/wally.png",
    greeting: "bot.greeting.wally",
  },
  {
    id: "Julia-Bot",
    nameEnglish: "Julia",
    namePersian: "جولیا",
    nameKey: "bot.name.julia",
    rating: 1880,
    descriptionKey: "bot.description.julia",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی دقیق با توانایی‌های تاکتیکی و استراتژیک؛ مناسب برای تمرین هماهنگی حمله و دفاع در میانه‌بازی.",
    category: "Advanced",
    image: "/bots/advanced/julia.png",
    country: "de",
    greeting: "bot.greeting.julia",
  },
  {
    id: "Miguel-Bot",
    nameEnglish: "Miguel",
    namePersian: "میگل",
    nameKey: "bot.name.miguel",
    rating: 1740,
    descriptionKey: "bot.description.miguel",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی هجومی با تمایل به ایجاد پیچیدگی‌های تاکتیکی؛ برای تمرین حملات برنده‌ساز و محاسبات ترکیبی مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/miguel.png",
    country: "es",
    greeting: "bot.greeting.miguel",
  },
  {
    id: "Xavier-Bot",
    nameEnglish: "Xavier",
    namePersian: "خاویر",
    nameKey: "bot.name.xavier",
    rating: 1920,
    descriptionKey: "bot.description.xavier",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی فنی با تمرکز بر دقت محاسبات و برنامه‌ریزی؛ مناسب برای تمرین بازی‌های پیچیده و حفظ مزیت فنی.",
    category: "Advanced",
    image: "/bots/advanced/xavier.png",
    country: "fr",
    greeting: "bot.greeting.xavier",
  },
  {
    id: "Olga-Bot",
    nameEnglish: "Olga",
    namePersian: "اولگا",
    nameKey: "bot.name.olga",
    rating: 1700,
    descriptionKey: "bot.description.olga",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی که ترکیبی از بازی دفاعی قوی و حملات سریع را ارائه می‌دهد؛ برای تمرین واکنش به تهدیدات ناگهانی مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/olga.png",
    country: "ru",
    greeting: "bot.greeting.olga",
  },
  {
    id: "Li-Bot",
    nameEnglish: "Li",
    namePersian: "لی",
    nameKey: "bot.name.li",
    rating: 1650,
    descriptionKey: "bot.description.li",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی چابک با تمایل به بازی‌های ترکیبی سریع؛ برای تمرین تاکتیک‌های موقعیتی و محاسبات سریع مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/li.png",
    country: "cn",
    greeting: "bot.greeting.li",
  },
  {
    id: "Charles-Bot",
    nameEnglish: "Charles",
    namePersian: "چارلز",
    nameKey: "bot.name.charles",
    rating: 1970,
    descriptionKey: "bot.description.charles",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی با سبک کلاسیک و تیز در محاسبات؛ مناسب برای بازیکنانی که می‌خواهند با سبک اصولی و دقیق تمرین کنند.",
    category: "Advanced",
    image: "/bots/advanced/charles.png",
    country: "gb",
    greeting: "bot.greeting.charles",
  },
  {
    id: "Fatima-Bot",
    nameEnglish: "Fatima",
    namePersian: "فاطیما",
    nameKey: "bot.name.fatima",
    rating: 1680,
    descriptionKey: "bot.description.fatima",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی چندوجهی با واکنش‌های هوشمندانه به اشتباهات حریف؛ برای تمرین بهره‌برداری از موقعیت‌های کوچک مناسب است.",
    category: "Advanced",
    image: "/bots/advanced/fatima.png",
    greeting: "bot.greeting.fatima",
  },
  {
    id: "Manuel-Bot",
    nameEnglish: "Manuel",
    namePersian: "مانوئل",
    nameKey: "bot.name.manuel",
    rating: 1830,
    descriptionKey: "bot.description.manuel",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی با استحکام پوزیسیونی و توانایی بازی در سطوح میانه تا پیشرفته؛ مناسب برای تمرین ساختارهای پیاده و میانه‌بازی.",
    category: "Advanced",
    image: "/bots/advanced/manuel.png",
    country: "es",
    greeting: "bot.greeting.manuel",
  },
  {
    id: "Oscar-Bot",
    nameEnglish: "Oscar",
    namePersian: "اسکار",
    nameKey: "bot.name.oscar",
    rating: 1760,
    descriptionKey: "bot.description.oscar",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رباتی منعطف با قابلیت ایجاد فشار در میانه‌بازی و تبدیل اشتباهات حریف به برتری؛ مناسب برای تمرین فشار مداوم.",
    category: "Advanced",
    image: "/bots/advanced/oscar.png",
    greeting: "bot.greeting.oscar",
  },
];

// ============================================================
// MASTER BOTS (1600-2200 Elo)
// ============================================================
export const MASTER_BOTS: Bot[] = [
  {
    id: "nora-master-001",
    nameEnglish: "Nora",
    namePersian: "نورا",
    nameKey: "bot.name.nora",
    rating: 2600,
    descriptionKey: "bot.description.nora",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "یک استاد تهاجمی با گرایش به بازی ترکیبی و حملات سریع؛ رفتار آموزشی دارد و پس از هر اشتباه، توضیح مختصر می‌دهد.",
    category: "Master",
    image: "/bots/master/nora.png",
    country: "us",
    greeting: "bot.greeting.nora",
  },
  {
    id: "noam-master-002",
    nameEnglish: "Noam",
    namePersian: "نوآم",
    nameKey: "bot.name.noam",
    rating: 2700,
    descriptionKey: "bot.description.noam",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "استادی محاسبه‌گر و دفاعی که تکیه‌گاه استراتژی طولانی‌مدت است؛ مناسب بازیکنانی که می‌خواهند محاسبات انتهایی را تقویت کنند.",
    category: "Master",
    image: "/bots/master/noam.png",
    country: "il",
    greeting: "bot.greeting.noam",
  },
  {
    id: "ahmed-master-003",
    nameEnglish: "Ahmed",
    namePersian: "احمد",
    nameKey: "bot.name.ahmed",
    rating: 2550,
    descriptionKey: "bot.description.ahmed",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "استادی متعادل با اولویت کنترل مرکز و بازی پوزیسیونی؛ توضیحات کوتاه‌وکاربردی در مورد اشتباهات می‌دهد.",
    category: "Master",
    image: "/bots/master/ahmed.png",
    country: "eg",
    greeting: "bot.greeting.ahmed",
  },
  {
    id: "sakura-master-004",
    nameEnglish: "Sakura",
    namePersian: "ساکورا",
    nameKey: "bot.name.sakura",
    rating: 2500,
    descriptionKey: "bot.description.sakura",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رویکرد خلاقانه و دید تاکتیکی بالا؛ ترکیب‌های غیرمتعارف را دوست دارد و برای تمرین تاکتیک مناسب است.",
    category: "Master",
    image: "/bots/master/sakura.png",
    country: "jp",
    greeting: "bot.greeting.sakura",
  },
  {
    id: "arjun-master-005",
    nameEnglish: "Arjun",
    namePersian: "آرجون",
    nameKey: "bot.name.arjun",
    rating: 2650,
    descriptionKey: "bot.description.arjun",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "استادی محکم با مبانی نظری قوی؛ به بازیکنان کمک می‌کند ایده‌های بازی وسط را بهتر درک کنند و پایان‌بازی‌ها را تقویت می‌کند.",
    category: "Master",
    image: "/bots/master/arjun.png",
    country: "in",
    greeting: "bot.greeting.arjun",
  },
  {
    id: "francis-master-006",
    nameEnglish: "Francis",
    namePersian: "فرانسیس",
    nameKey: "bot.name.francis",
    rating: 2620,
    descriptionKey: "bot.description.francis",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "رویه‌ای متفکر و حساب‌شده؛ مناسب برای مطالعه بازی‌های استراتژیک و بازنمایی ایده‌های کلاسیک شطرنج.",
    category: "Master",
    image: "/bots/master/francis.png",
    country: "fr",
    greeting: "bot.greeting.francis",
  },
  {
    id: "sofia-master-007",
    nameEnglish: "Sofia",
    namePersian: "صوفیا",
    nameKey: "bot.name.sofia",
    rating: 2580,
    descriptionKey: "bot.description.sofia",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "سبک بازی انعطاف‌پذیر؛ ترکیبی از برنامه‌ریزی پوزیسیونی و واکنش‌های تاکتیکی سریع، مناسب بازیکنان میانی-پیشرفته.",
    category: "Master",
    image: "/bots/master/sofia.png",
    country: "bg",
    greeting: "bot.greeting.sofia",
  },
  {
    id: "alexander-master-008",
    nameEnglish: "Alexander",
    namePersian: "الکساندر",
    nameKey: "bot.name.alexander",
    rating: 2680,
    descriptionKey: "bot.description.alexander",
    descriptionEnglish: "An advanced bot with a focus on tactical play and high tactical skills; suitable for intermediate to advanced players looking to improve their tactical skills.",
    descriptionPersian: "استاد بزرگ با سبک جهان‌شمول؛ بازی او دقیق و بدون ریسک‌های غیرضروری است و برای یادگیری بازی استاندارد ایده‌آل است.",
    category: "Master",
    image: "/bots/master/alexander.png",
    country: "ru",
    greeting: "bot.greeting.alexander",
  },
];

// ============================================================
// PERSIAN CREATORS (1600-2200 Elo)
// ============================================================
export const PERSIAN_CREATORS_BOTS: Bot[] = [
  {
    id: "mohammad-shah-moradi",
    nameKey: "Bots.Bot.MohammadShahMoradi.Name",
    nameEnglish: "Mohammad Shah Moradi",
    namePersian: "محمد شاه‌مرادی",
    rating: 2158,
    descriptionKey: "Bots.Bot.MohammadShahMoradi.Desc",
    descriptionEnglish: "A Persian chess content creator and Candidate Master with a YouTube channel 'Enjoy Chess' featuring game analysis and educational content.",
    descriptionPersian: "تولیدکننده محتوای شطرنج پارسی و نامزد استاد با کانال یوتیوب «Enjoy Chess» شامل تحلیل بازی‌ها و محتوای آموزشی.",
    category: "PersianCreators",
    image: "/bots/persiancreators/mohammad-shah-moradi-bot.png",
    country: "ir",
    cardStyle: "youtube",
    youtubeUrl: "https://www.youtube.com/@enjoychess",
  },
  {
    id: "behrang-mehdiabadi",
    nameKey: "Bots.Bot.BehrangMehdiabadi.Name",
    nameEnglish: "Behrang Mehdiabadi",
    namePersian: "بهرنگ مهدی‌آبادی",
    rating: 1948,
    descriptionKey: "Bots.Bot.BehrangMehdiabadi.Desc",
    descriptionEnglish: "A Persian chess instructor with YouTube channel 'Chess with Behrang' teaching tactics, techniques, and analysis, also leading a Lichess academy.",
    descriptionPersian: "مربی شطرنج پارسی با کانال یوتیوب «Chess with Behrang» آموزش تاکتیک‌ها، تکنیک‌ها و تحلیل، همچنین رهبری آکادمی در Lichess.",
    category: "PersianCreators",
    image: "/bots/persiancreators/behrang-mehdiabadi-bot.png",
    country: "ir",
    cardStyle: "youtube",
    youtubeUrl: "https://www.youtube.com/@Chess_with_Behrang",
  },
];

export const OTHER_BOTS: Bot[] = [
  // Champions, Musicians, TopPlayers...
  // Leaving these empty for now in this update to save space, but logically they would be here.
  // The user only requested redesign for the rating system, so valid standard bots are priority.
  // Existing bots can be migrated on demand.
];
// Helper functions
export function getAllBots(): Bot[] {
  return [
    ...BEGINNER_BOTS,
    ...INTERMEDIATE_BOTS,
    ...ADVANCED_BOTS,
    ...MASTER_BOTS,
    ...PERSIAN_CREATORS_BOTS,
  ];
}

export function getBotsByCategory(category: BotCategory): Bot[] {
  switch (category) {
    case "Beginner":
      return BEGINNER_BOTS;
    case "Intermediate":
      return INTERMEDIATE_BOTS;
    case "Advanced":
      return ADVANCED_BOTS;
    case "Master":
      return MASTER_BOTS;
    case "PersianCreators":
      return PERSIAN_CREATORS_BOTS;
    default:
      return [];
  }
}
